# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=256, verbose_name='Название города')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=256, verbose_name='Название события')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Начало события')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображается на сайте')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка на событие')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.City')),
            ],
            options={
                'ordering': ['date', '-id'],
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
