# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-19 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170214_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_translation_alive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='translation_video_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
