# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-19 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170219_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_registration_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='register_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
