# Generated by Django 2.2.20 on 2021-05-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_place_and_time_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to='events', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='event',
            name='image_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на картинку мероприятия'),
        ),
    ]
