# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Главная новость'),
        ),
    ]
