# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-01 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Показывать'),
        ),
    ]
