# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-02 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20161001_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='language',
            field=models.CharField(choices=[('ru', 'ru'), ('en', 'en')], default='en', max_length=2, verbose_name='Язык'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='section',
            field=models.CharField(blank=True, max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.CharField(choices=[('pythondigest', 'pythondigest'), ('python.ru', 'python.ru')], max_length=32, verbose_name='Источник'),
        ),
    ]
