# Generated by Django 2.0.1 on 2018-06-24 16:39

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20161002_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_our',
            field=models.BooleanField(default=False, verbose_name='Наш пост?'),
        ),
        migrations.AddField(
            model_name='article',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='article',
            name='language',
            field=models.CharField(choices=[('ru', '🇷🇺'), ('en', '🇬🇧')], max_length=2, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
