# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-13 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20161002_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_our',
            field=models.BooleanField(default=False, verbose_name='Наш пост?'),
        ),
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
    ]
