# Generated by Django 2.0.1 on 2018-06-28 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20180624_1939'),
        ('news', '0007_auto_20180225_2107'),
    ]

    operations = [
    ]
