# Generated by Django 2.2.20 on 2021-04-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20201022_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_recommend',
            field=models.BooleanField(default=True, verbose_name='Рекомендовать этот опст?'),
        ),
    ]
