# Generated by Django 2.2.20 on 2021-05-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_article_is_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_recommend',
            field=models.BooleanField(default=True, verbose_name='Рекомендовать этот пост?'),
        ),
    ]
