# Generated by Django 2.2.20 on 2021-04-29 13:53

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('top_badge', models.CharField(max_length=32, verbose_name='значок в верхней части')),
                ('color', models.CharField(max_length=32, verbose_name='Background color')),
                ('logo', models.CharField(max_length=140, verbose_name='Логотип')),
                ('title', models.CharField(max_length=140, verbose_name='Заголовок слайда')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимость слайда')),
                ('date', models.CharField(max_length=140, verbose_name='Дата проведение проекта')),
                ('description', models.CharField(max_length=300, verbose_name='Описание проекта')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
