# Generated by Django 2.2.20 on 2021-05-04 14:34

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=32)),
                ('link', models.CharField(max_length=120)),
                ('img', models.ImageField(blank=True, upload_to='sponsor', verbose_name='Изображение')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
